{% set name = "porespy" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 109c5e2d584e12e14d62626159c1324d3dc0e0cb3743e6170e5fbf1f534e8289

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - scipy
    - scikit-image
    - matplotlib-base
    - pandas
    - imageio
    - pyevtk
    - array_split
    - transforms3d
    - tqdm
    - numba
    - dask[complete]
    - openpnm
    - edt

test:
  imports:
    - porespy

about:
  home: https://github.com/PMEAL/porespy/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A set of tools for characterizing and analying 3D images of porous materials
  description: PoreSpy is a collection of image analysis tool used to extract information from 3D images of porous materials (typically obtained from X-ray tomography). There are many packages that offer generalized image analysis tools (i.e Skimage and Scipy.NDimage in the Python environment, ImageJ, MatLab's Image Processing
    Toolbox), but the all require building up complex scripts or macros to accomplish tasks of specific use to porous media. The aim of PoreSpy is to provide a set of pre-written tools for all the common porous media measurements.

  doc_url: https://porespy.readthedocs.io/en/dev/
  dev_url: https://github.com/PMEAL/porespy/

extra:
  recipe-maintainers:
    - jgostick
    - ma-sadeghi
